### ISSUE TITLE
vim-lua repeated twice

### ISSUE THREAD

**Issue by fetsorn** [cideM/dotfiles#4]
https://github.com/cideM/dotfiles/blob/c25664ef7515abc4379b109455bd2f334fb6cdb2/flake.nix#L89

**Comment by cideM** [comment]
I really have to do something about GitHub notifications. Somehow I'm spammed with random stuff but miss issues created for my own repositories. Thank you very much for reporting this!

**Comment by cideM** [comment]
...and fixed 🎊
